// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrPfmUSYx1rAlFH_NGF_3zdvx266T3-Q',
    appId: '1:1010964795515:web:dce9da7f18b721da6cd2de',
    messagingSenderId: '1010964795515',
    projectId: 'odyssey-508fc',
    authDomain: 'odyssey-508fc.firebaseapp.com',
    storageBucket: 'odyssey-508fc.appspot.com',
    measurementId: 'G-0EMGL2YDKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLtEClsxFFf8lM-oaAMGPXsG6LKsSjwM',
    appId: '1:1010964795515:android:f823648e9fbd26176cd2de',
    messagingSenderId: '1010964795515',
    projectId: 'odyssey-508fc',
    storageBucket: 'odyssey-508fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3YhG7diKucR4gVelt0SjpTej4IDZRZGo',
    appId: '1:1010964795515:ios:62791c3ae4583fc16cd2de',
    messagingSenderId: '1010964795515',
    projectId: 'odyssey-508fc',
    storageBucket: 'odyssey-508fc.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3YhG7diKucR4gVelt0SjpTej4IDZRZGo',
    appId: '1:1010964795515:ios:62791c3ae4583fc16cd2de',
    messagingSenderId: '1010964795515',
    projectId: 'odyssey-508fc',
    storageBucket: 'odyssey-508fc.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZrPfmUSYx1rAlFH_NGF_3zdvx266T3-Q',
    appId: '1:1010964795515:web:cce86a92e41368e46cd2de',
    messagingSenderId: '1010964795515',
    projectId: 'odyssey-508fc',
    authDomain: 'odyssey-508fc.firebaseapp.com',
    storageBucket: 'odyssey-508fc.appspot.com',
    measurementId: 'G-JCPFNV8TF2',
  );

}